version: '3.8'
services:

  #
  # API calls are routed via the API Gateway at the https://api.mycompany.com:444 base URL
  #
  api-gateway:
    image: kong:2.5.0-alpine
    hostname: apigatewayhost
    ports:
      - 444:3000
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - ./kong-bff-plugin/plugin:/usr/local/share/lua/5.1/kong/plugins/bff-token
      - ./.certs/localhost/mycompany.com.ssl.pem:/usr/local/share/certs/mycompany.com.ssl.pem
      - ./.certs/localhost/mycompany.com.ssl.key:/usr/local/share/certs/mycompany.com.ssl.key
      - ./.certs/localhost/mycompany.com.ca.pem:/usr/local/share/certs/mycompany.com.ca.pem
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3000 ssl'
      KONG_SSL_CERT: '/usr/local/share/certs/mycompany.com.ssl.pem'
      KONG_SSL_CERT_KEY: './usr/local/share/certs/mycompany.com.ssl.key'
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: './usr/local/share/certs/mycompany.com.ca.pem'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,bff-token'

  #
  # The Back End for Front End API performs OAuth and cookie issuing work for the SPA
  # The SPA calls the BFF via the gateway at https://api.mycompany.com:444/bff
  #
  back-end-for-front-end-api:
    image: curity-bff-api:1.0.0
    hostname: bffapihost
    volumes:
      - ./bff-config.js:/usr/bff-api/dist/config.js

